model:
  var_type: fixedsmall
  ema: false
  type: pipeline

diffusion:
  beta_schedule: linear
  beta_start: 0.0001
  beta_end: 0.02
  num_diffusion_timesteps: 1000

training:
  n_iters: 1000
  snapshot_freq: 200
  log_freq: 20
  gamma: 1.0
  lmbda: 0.0

optim:
  grad_clip: 1.0
  optimizer: adam
  lr: 1e-4

data:
  image_size: 256
  channels: 3
  n_classes: 2
